### ISSUE TITLE
Code Format, Style, and Indentation

### ISSUE THREAD

**Issue by jordanwillis** [gerardin/prj-rev-bwfs-dasmoto#1]
Both your HTML and CSS code is looking really good!  One thing to keep in mind is to watch your overall code format, style, and indentation.  It is a best practice to make sure that all elements that are structurally at the same level be lined up on the same indentation line and to indent nested elements by 2-spaces.  It is also a good practice to put your open elements in a different line that the content as well as the closing element tag.

Here is an example of what I mean.  Instead of this.., 

```
  <body>

<h1>Dasmoto's Arts & Crafts</h1>

<div class="item">
<h2 id="brush">Brushes</h2>
<img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg" alt="Brushes" />
<h3>Hacksaw Brushes</h3>
<p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes.</p>
<p><span class="price">Starting at $3.00 / brush. </p>
```

Applying code format, style, and indentation best practices would look like this...

```
  <body>
    <h1>Dasmoto's Arts & Crafts</h1>
    
    <div class="item">
      <h2 id="brush">Brushes</h2>
      <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg" alt="Brushes" />
      <h3>Hacksaw Brushes</h3>
      <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes.</p>
      <p><span class="price">Starting at $3.00 / brush.</span></p>
    </div>
    
    <!-- rest of your code -->
```

This just ensures that your code is very readable which is really important for large projects or projects with several team mates.  I have encountered situations where the root cause of bugs was nothing more than getting something in the wrong place on account of poor code style/indentation.

**Comment by gerardin** [comment]
Thank you for the feedback, i've resubmitted my files with hopefully better indentation.
