### ISSUE TITLE
Unclosed <span>

### ISSUE THREAD

**Issue by jordanwillis** [gerardin/prj-rev-bwfs-dasmoto#2]
I also happened to come across what is probably just a typo.  There is an unclosed `<span>` element in your brushes section.

https://github.com/gerardin/prj-rev-bwfs-dasmoto/blob/master/Project1/index.html#L18

Fortunately, modern browsers these days are quite lenient when encountered HTML structural issues, but it is always good to run your web site through a validator just to make sure these types of things are discovered and corrected.

https://validator.w3.org/nu/?doc=https%3A%2F%2Frawgit.com%2Fgerardin%2Fprj-rev-bwfs-dasmoto%2Fmaster%2FProject1%2Findex.html

**Comment by gerardin** [comment]
Sorry about that. I've updated the missing closing <span> element.
