### ISSUE TITLE
Unstyled Prices

### ISSUE THREAD

**Issue by jordanwillis** [gerardin/prj-rev-bwfs-dasmoto#3]
When I was reviewing the visual look of your project I noticed that the price in each section was not being colored blue per the project specification.

After further review it looks like you had the right intention and pretty much did all the work, but got caught up with a simple mistake.  Make sure that your CSS selectors match how they actually being used.  For example, in your HTML you are using the `class` "price"

https://github.com/gerardin/prj-rev-bwfs-dasmoto/blob/master/Project1/index.html#L18
https://github.com/gerardin/prj-rev-bwfs-dasmoto/blob/master/Project1/index.html#L25
https://github.com/gerardin/prj-rev-bwfs-dasmoto/blob/master/Project1/index.html#L31

But the selector in your CSS is using an `ID`...

https://github.com/gerardin/prj-rev-bwfs-dasmoto/blob/master/Project1/resources/style.css#L22

So in order for the prices to get their styles correctly applied we either need to change the CSS selector or change the HTML to use ID instead of class.  In this situation, since there are multiple elements that need to have the same style, then it's best to use a class (IDs are intended for single elements).  So we just need to update the selector in our CSS.

```
.price {
  color: blue;
}
```

**Comment by jordanwillis** [comment]
On further review, I see that you did also define a selector for your `.price` class.

https://github.com/gerardin/prj-rev-bwfs-dasmoto/blob/master/Project1/resources/style.css#L35

However, in this case it is not being applied because there is a syntax error (e.g. missing semi colon) that is causing an error.  Here is the correct CSS with proper format applied as well (e.g. a space in between the property name and property value)...

```
.price {
  color: blue;
  font-weight: bold;
}
```

Lastly, to prevent confusion in your code you will want to make sure that you never use the same name for IDs and classes.

**Comment by gerardin** [comment]
Thank you so much for the feedback. I had initially created .price but could not work out why it wasn't working which is why i created the other class. I've updated the typo and the prices now show up in the blue font. Thanks again.
