### ISSUE TITLE
Page level components

### ISSUE THREAD

**Issue by jordanwillis** [gerardin/prj-rev-bwfs-dasmoto#4]
Another recommendation is to make sure that each component in your page is wrapped in an element so that it is self contained.  Here is an example of what I mean...

```
<div class="item">
  <h2 id="frame">Frames</h2>
  <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/frames.jpeg" alt="Frames" />
  <h3>Art Frames (assorted) </h3>
  <p>Assorted frames made of different material, including MDF, birchwood, and PDE. Select frames can be sanded and painted according to your needs. </p>
  <p><span class="price">Starting at $2.00 / frame.</span></p>
</di>
```

It looks like you had this idea in mind and even started implementing it (nice work!), but ended up not doing it for each individual container.

**Comment by gerardin** [comment]
Thank you, i've now updated it to apply this to each container.
